package io.smsc.db.migration;

import io.smsc.converters.CryptoConverter;
import io.smsc.model.Permission;
import io.smsc.model.Role;
import io.smsc.model.User;
import io.smsc.model.crud.*;
import io.smsc.model.customer.Customer;
import io.smsc.model.customer.CustomerContact;
import io.smsc.model.customer.Salutation;
import io.smsc.model.customer.Type;
import io.smsc.model.dashboard.*;
import io.smsc.repository.crud.crudClassMetaData.CrudClassMetaDataRepository;
import io.smsc.repository.crud.crudMetaFormData.CrudMetaFormDataRepository;
import io.smsc.repository.crud.crudMetaGridData.CrudMetaGridDataRepository;
import io.smsc.repository.crud.metaDataPropertyBindingParameter.MetaDataPropertyBindingParameterRepository;
import io.smsc.repository.customer.customer.CustomerRepository;
import io.smsc.repository.customer.customerContact.CustomerContactRepository;
import io.smsc.repository.dashboard.dashboard.DashboardRepository;
import io.smsc.repository.dashboard.dashboardBox.DashboardBoxRepository;
import io.smsc.repository.dashboard.dashboardBoxType.DashboardBoxTypeRepository;
import io.smsc.repository.permission.PermissionRepository;
import io.smsc.repository.role.RoleRepository;
import io.smsc.repository.user.UserRepository;
import org.flywaydb.core.api.migration.spring.SpringJdbcMigration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * This class is used for providing java based flyway migration service
 * using custom configuration {@link io.smsc.config.FlywayConfiguration}.
 *
 * @author  Nazar Lipkovskyy
 * @since   0.0.1-SNAPSHOT
 */
@Component
public class V1_2__populateDB implements SpringJdbcMigration {

    private final PermissionRepository permissionRepository;

    private final RoleRepository roleRepository;

    private UserRepository userRepository;

    private final CrudClassMetaDataRepository crudClassMetaDataRepository;

    private final CrudMetaFormDataRepository crudMetaFormDataRepository;

    private final CrudMetaGridDataRepository crudMetaGridDataRepository;

    private final MetaDataPropertyBindingParameterRepository metaDataPropertyBindingParameterRepository;

    private final CustomerRepository customerRepository;

    private final CustomerContactRepository customerContactRepository;

    private final DashboardRepository dashboardRepository;

    private final DashboardBoxRepository dashboardBoxRepository;

    private final DashboardBoxTypeRepository dashboardBoxTypeRepository;

    /**
     * String, which is used for {@link org.springframework.security.crypto.encrypt.TextEncryptor} creating
     */
    @Value("${encrypt.key}")
    private String secretKey;

    @Autowired
    public V1_2__populateDB(PermissionRepository permissionRepository, RoleRepository roleRepository, UserRepository userRepository,
                            CrudClassMetaDataRepository crudClassMetaDataRepository, CrudMetaFormDataRepository crudMetaFormDataRepository,
                            CrudMetaGridDataRepository crudMetaGridDataRepository, MetaDataPropertyBindingParameterRepository metaDataPropertyBindingParameterRepository,
                            CustomerRepository customerRepository, CustomerContactRepository customerContactRepository, DashboardRepository dashboardRepository,
                            DashboardBoxRepository dashboardBoxRepository, DashboardBoxTypeRepository dashboardBoxTypeRepository) {
        this.permissionRepository = permissionRepository;
        this.roleRepository = roleRepository;
        this.userRepository = userRepository;
        this.crudClassMetaDataRepository = crudClassMetaDataRepository;
        this.crudMetaFormDataRepository = crudMetaFormDataRepository;
        this.crudMetaGridDataRepository = crudMetaGridDataRepository;
        this.metaDataPropertyBindingParameterRepository = metaDataPropertyBindingParameterRepository;
        this.customerRepository = customerRepository;
        this.customerContactRepository = customerContactRepository;
        this.dashboardRepository = dashboardRepository;
        this.dashboardBoxRepository = dashboardBoxRepository;
        this.dashboardBoxTypeRepository = dashboardBoxTypeRepository;
    }

    /**
     * Executes this migration. The execution will automatically take place within a transaction, when the underlying
     * database supports it.
     *
     * @param  jdbcTemplate The jdbcTemplate to use to execute statements.
     * @throws Exception    when the migration failed.
     */
    public void migrate(JdbcTemplate jdbcTemplate) throws Exception {
        Permission permission1 = new Permission(null, "USER_READ");
        Permission permission2 = new Permission(null, "USER_UPDATE");
        Permission permission3 = new Permission(null, "USER_CREATE");
        Permission permission4 = new Permission(null, "USER_DELETE");
        Permission permission5 = new Permission(null, "USER_READ_OWN");
        Permission permission6 = new Permission(null, "USER_UPDATE_OWN");
        Permission permission7 = new Permission(null, "ROLE_READ");
        Permission permission8 = new Permission(null, "ROLE_UPDATE");
        Permission permission9 = new Permission(null, "ROLE_CREATE");
        Permission permission10 = new Permission(null, "ROLE_DELETE");
        Permission permission11 = new Permission(null, "PERMISSION_READ");
        Permission permission12 = new Permission(null, "PERMISSION_UPDATE");
        Permission permission13 = new Permission(null, "PERMISSION_CREATE");
        Permission permission14 = new Permission(null, "PERMISSION_DELETE");
        Permission permission15 = new Permission(null, "CRUD_CLASS_META_DATA_READ");
        Permission permission16 = new Permission(null, "CRUD_CLASS_META_DATA_UPDATE");
        Permission permission17 = new Permission(null, "CRUD_CLASS_META_DATA_CREATE");
        Permission permission18 = new Permission(null, "CRUD_CLASS_META_DATA_DELETE");
        Permission permission19 = new Permission(null, "CRUD_META_FORM_DATA_READ");
        Permission permission20 = new Permission(null, "CRUD_META_FORM_DATA_UPDATE");
        Permission permission21 = new Permission(null, "CRUD_META_FORM_DATA_CREATE");
        Permission permission22 = new Permission(null, "CRUD_META_FORM_DATA_DELETE");
        Permission permission23 = new Permission(null, "CRUD_META_GRID_DATA_READ");
        Permission permission24 = new Permission(null, "CRUD_META_GRID_DATA_UPDATE");
        Permission permission25 = new Permission(null, "CRUD_META_GRID_DATA_CREATE");
        Permission permission26 = new Permission(null, "CRUD_META_GRID_DATA_DELETE");
        Permission permission27 = new Permission(null, "META_DATA_PROPERTY_BINDING_PARAMETER_READ");
        Permission permission28 = new Permission(null, "META_DATA_PROPERTY_BINDING_PARAMETER_UPDATE");
        Permission permission29 = new Permission(null, "META_DATA_PROPERTY_BINDING_PARAMETER_CREATE");
        Permission permission30 = new Permission(null, "META_DATA_PROPERTY_BINDING_PARAMETER_DELETE");
        Permission permission31 = new Permission(null, "CUSTOMER_READ");
        Permission permission32 = new Permission(null, "CUSTOMER_UPDATE");
        Permission permission33 = new Permission(null, "CUSTOMER_CREATE");
        Permission permission34 = new Permission(null, "CUSTOMER_DELETE");
        Permission permission35 = new Permission(null, "CUSTOMER_CONTACT_READ");
        Permission permission36 = new Permission(null, "CUSTOMER_CONTACT_UPDATE");
        Permission permission37 = new Permission(null, "CUSTOMER_CONTACT_CREATE");
        Permission permission38 = new Permission(null, "CUSTOMER_CONTACT_DELETE");
        Permission permission39 = new Permission(null, "DASHBOARD_READ");
        Permission permission40 = new Permission(null, "DASHBOARD_UPDATE");
        Permission permission41 = new Permission(null, "DASHBOARD_CREATE");
        Permission permission42 = new Permission(null, "DASHBOARD_DELETE");
        Permission permission43 = new Permission(null, "DASHBOARD_BOX_READ");
        Permission permission44 = new Permission(null, "DASHBOARD_BOX_UPDATE");
        Permission permission45 = new Permission(null, "DASHBOARD_BOX_CREATE");
        Permission permission46 = new Permission(null, "DASHBOARD_BOX_DELETE");
        Permission permission47 = new Permission(null, "DASHBOARD_BOX_TYPE_READ");
        Permission permission48 = new Permission(null, "DASHBOARD_BOX_TYPE_UPDATE");
        Permission permission49 = new Permission(null, "DASHBOARD_BOX_TYPE_CREATE");
        Permission permission50 = new Permission(null, "DASHBOARD_BOX_TYPE_DELETE");
        Role role_user = new Role(null, "ROLE_USER");
        Role role_admin = new Role(null, "ROLE_ADMIN");
        User user = new User(null,"user","password","userName","userSurname","user@gmail.com",true,false);
        User admin = new User(null,"admin","admin","adminName","adminSurname","admin@gmail.com",true,false);
        permissionRepository.save(permission1);
        permissionRepository.save(permission2);
        permissionRepository.save(permission3);
        permissionRepository.save(permission4);
        permissionRepository.save(permission5);
        permissionRepository.save(permission6);
        permissionRepository.save(permission7);
        permissionRepository.save(permission8);
        permissionRepository.save(permission9);
        permissionRepository.save(permission10);
        permissionRepository.save(permission11);
        permissionRepository.save(permission12);
        permissionRepository.save(permission13);
        permissionRepository.save(permission14);
        permissionRepository.save(permission15);
        permissionRepository.save(permission16);
        permissionRepository.save(permission17);
        permissionRepository.save(permission18);
        permissionRepository.save(permission19);
        permissionRepository.save(permission20);
        permissionRepository.save(permission21);
        permissionRepository.save(permission22);
        permissionRepository.save(permission23);
        permissionRepository.save(permission24);
        permissionRepository.save(permission25);
        permissionRepository.save(permission26);
        permissionRepository.save(permission27);
        permissionRepository.save(permission28);
        permissionRepository.save(permission29);
        permissionRepository.save(permission30);
        permissionRepository.save(permission31);
        permissionRepository.save(permission32);
        permissionRepository.save(permission33);
        permissionRepository.save(permission34);
        permissionRepository.save(permission35);
        permissionRepository.save(permission36);
        permissionRepository.save(permission37);
        permissionRepository.save(permission38);
        permissionRepository.save(permission39);
        permissionRepository.save(permission40);
        permissionRepository.save(permission41);
        permissionRepository.save(permission42);
        permissionRepository.save(permission43);
        permissionRepository.save(permission44);
        permissionRepository.save(permission45);
        permissionRepository.save(permission46);
        permissionRepository.save(permission47);
        permissionRepository.save(permission48);
        permissionRepository.save(permission49);
        permissionRepository.save(permission50);
        Set<Permission> userPermission = new HashSet<>();
        userPermission.add(permissionRepository.findOne(5L));
        userPermission.add(permissionRepository.findOne(6L));
        role_user.setPermissions(userPermission);
        role_admin.setPermissions(new HashSet<>(permissionRepository.findAll()));
        Role user_role = roleRepository.save(role_user);
        Role admin_role = roleRepository.save(role_admin);
        Set<Role> userRole = new HashSet<>();
        userRole.add(user_role);
        Set<Role> adminRole = new HashSet<>();
        adminRole.add(admin_role);
        user.setRoles(userRole);
        admin.setRoles(adminRole);
        CryptoConverter.encrypt(user,secretKey);
        CryptoConverter.encrypt(admin,secretKey);
        User new_user = userRepository.save(user);
        User new_admin = userRepository.save(admin);
        CrudClassMetaData crudClassMetaData1 = new CrudClassMetaData(null, "CrudMetaGridData", "columnWidth", true, null);
        CrudClassMetaData crudClassMetaData2 = new CrudClassMetaData(null, "CrudMetaFormData", "fieldLayoutGridPosition", true, null);
        CrudClassMetaData crudClassMetaData3 = new CrudClassMetaData(null, "CrudClassMetaData", "className", true, null);
        CrudClassMetaData crudClassMetaData4 = new CrudClassMetaData(null, "Customer", "customerId", true, null);
        CrudClassMetaData crudClassMetaData5 = new CrudClassMetaData(null,"User", "name", true, null);
        CrudClassMetaData crudClassMetaData6 = new CrudClassMetaData(null,"MetaDataPropertyBindingParameter", "operator", true, null);
        CrudClassMetaData crudClassMetaData7 = new CrudClassMetaData(null,"Dashboard", "name", true, null);
        CrudClassMetaData crudClassMetaData8 = new CrudClassMetaData(null,"DashboardBox", "name", true, null);
        CrudClassMetaData crudClassMetaData9 = new CrudClassMetaData(null,"DashboardBoxType", "name", true, null);
        CrudClassMetaData crudClassMetaData10 = new CrudClassMetaData(null,"Role", "name", true, null);
        CrudClassMetaData crudClassMetaData11 = new CrudClassMetaData(null,"Permission", "name", true, null);
        CrudClassMetaData crudClassMetaData12 = new CrudClassMetaData(null,"CustomerContact", "emailAddress", true, null);
        CrudClassMetaData newCrudClassMetaData1 = crudClassMetaDataRepository.save(crudClassMetaData1);
        CrudClassMetaData newCrudClassMetaData2 = crudClassMetaDataRepository.save(crudClassMetaData2);
        CrudClassMetaData newCrudClassMetaData3 = crudClassMetaDataRepository.save(crudClassMetaData3);
        CrudClassMetaData newCrudClassMetaData4 = crudClassMetaDataRepository.save(crudClassMetaData4);
        CrudClassMetaData newCrudClassMetaData5 = crudClassMetaDataRepository.save(crudClassMetaData5);
        CrudClassMetaData newCrudClassMetaData6 = crudClassMetaDataRepository.save(crudClassMetaData6);
        CrudClassMetaData newCrudClassMetaData7 = crudClassMetaDataRepository.save(crudClassMetaData7);
        CrudClassMetaData newCrudClassMetaData8 = crudClassMetaDataRepository.save(crudClassMetaData8);
        CrudClassMetaData newCrudClassMetaData9 = crudClassMetaDataRepository.save(crudClassMetaData9);
        CrudClassMetaData newCrudClassMetaData10 = crudClassMetaDataRepository.save(crudClassMetaData10);
        CrudClassMetaData newCrudClassMetaData11 = crudClassMetaDataRepository.save(crudClassMetaData11);
        CrudClassMetaData newCrudClassMetaData12 = crudClassMetaDataRepository.save(crudClassMetaData12);
        CrudMetaFormData crudMetaFormData1 = new CrudMetaFormData(null, "fromProperty", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData2 = new CrudMetaFormData(null, "toProperty", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData3 = new CrudMetaFormData(null, "combineOperator", true, true, null, 3.0, "AND,OR,NOT", null, null, null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData4 = new CrudMetaFormData(null, "operator", true, true, null, 4.0, "EQUALS,MORE,LESS,MORE_OR_EQUALS,LESS_OR_EQUALS,MORE_OR_LESS,LIKE,BETWEEN,IS,INSTANCE_OF,MATCHES", null, null, null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData5 = new CrudMetaFormData(null, "crudMetaFormData", true, true, null, 3.0, "Link", "CrudMetaFormData", "crud-meta-form-data", null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData6 = new CrudMetaFormData(null, "crudMetaGridData", true, true, null, 4.0, "Link", "CrudMetaGridData", "crud-meta-grid-data", null, newCrudClassMetaData6);
        CrudMetaFormData crudMetaFormData7 = new CrudMetaFormData(null, "columnWidth", true, true, null, 1.0, "Double", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData8 = new CrudMetaFormData(null, "property", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData9 = new CrudMetaFormData(null, "editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData10 = new CrudMetaFormData(null, "visible", true, true, null, 4.0, "Boolean", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData11 = new CrudMetaFormData(null, "decorator", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData12 = new CrudMetaFormData(null, "order", true, true, null, 6.0, "Double", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData13 = new CrudMetaFormData(null, "crudClassMetaData", true, true, null, 7.0, "Link", "CrudClassMetaData", "crud-class-meta-data", null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData14 = new CrudMetaFormData(null, "bindingProperties", true, true, null, 8.0, "Linkset", "MetaDataPropertyBindingParameter", "meta-data-property-binding-parameters", null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData15 = new CrudMetaFormData(null, "type", true, true, null, 9.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData16 = new CrudMetaFormData(null, "linkedClass", true, true, null, 10.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData17 = new CrudMetaFormData(null, "linkedRepository", true, true, null, 11.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaFormData crudMetaFormData18 = new CrudMetaFormData(null, "fieldLayoutGridPosition", true, true, null, 1.0, "String", null, null, null,newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData19 = new CrudMetaFormData(null, "property", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData20 = new CrudMetaFormData(null, "editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData21 = new CrudMetaFormData(null, "visible", true, true, null, 4.0, "Boolean", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData22 = new CrudMetaFormData(null, "decorator", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData23 = new CrudMetaFormData(null, "order", true, true, null, 6.0, "Double", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData24 = new CrudMetaFormData(null, "crudClassMetaData", true, true, null, 7.0, "Link", "CrudClassMetaData", "crud-class-meta-data", null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData25 = new CrudMetaFormData(null, "bindingProperties", true, true, null, 8.0, "Linkset", "MetaDataPropertyBindingParameter", "meta-data-property-binding-parameters", null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData26 = new CrudMetaFormData(null, "type", true, true, null, 9.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData27 = new CrudMetaFormData(null, "linkedClass", true, true, null, 10.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData28 = new CrudMetaFormData(null, "linkedRepository", true, true, null, 11.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaFormData crudMetaFormData29 = new CrudMetaFormData(null,"customerId", true, true, null, 1.0, "Double", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData30 = new CrudMetaFormData(null,"companyName", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData31 = new CrudMetaFormData(null,"street", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData32 = new CrudMetaFormData(null,"street2", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData33 = new CrudMetaFormData(null,"postcode", true, true, null,5.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData34 = new CrudMetaFormData(null,"country", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData35 = new CrudMetaFormData(null,"city", true, true, null, 7.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData36 = new CrudMetaFormData(null,"vatid", true, true, null, 8.0, "Double", null, null, null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData37 = new CrudMetaFormData(null,"contacts", true, true, null, 9.0, "Linkset", "CustomerContact", "customer-contacts", null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData38 = new CrudMetaFormData(null,"users", true, true, null, 10.0, "Linkset", "User", "users", null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData39 = new CrudMetaFormData(null,"parentCustomer", true, true, null, 11.0, "Link", "Customer", "customers", null, newCrudClassMetaData4);
        CrudMetaFormData crudMetaFormData40 = new CrudMetaFormData(null,"firstname", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData41 = new CrudMetaFormData(null,"surname", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData42 = new CrudMetaFormData(null,"phone", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData43 = new CrudMetaFormData(null,"mobilePhone", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData44 = new CrudMetaFormData(null,"fax", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData45 = new CrudMetaFormData(null,"emailAddress", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData46 = new CrudMetaFormData(null,"customer", true, true, null, 7.0, "Link", "Customer", "customers", null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData47 = new CrudMetaFormData(null,"type", true, true, null, 8.0, "CEO,TECHNICAL,PRIMARY", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData48 = new CrudMetaFormData(null,"salutation", true, true, null, 9.0, " MR,MRS", null, null, null, newCrudClassMetaData12);
        CrudMetaFormData crudMetaFormData49 = new CrudMetaFormData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData7);
        CrudMetaFormData crudMetaFormData50 = new CrudMetaFormData(null,"icon", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData7);
        CrudMetaFormData crudMetaFormData51 = new CrudMetaFormData(null,"user", true, true, null, 3.0, "Link", "User", "users", null, newCrudClassMetaData7);
        CrudMetaFormData crudMetaFormData52 = new CrudMetaFormData(null,"dashboardBoxes", true, true, null, 4.0, "Linkset", "DashboardBox", "dashboard-boxes", null, newCrudClassMetaData7);
        CrudMetaFormData crudMetaFormData53 = new CrudMetaFormData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData54 = new CrudMetaFormData(null,"description", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData55 = new CrudMetaFormData(null,"dashboardBoxType", true, true, null, 3.0, "Link", "DashboardBoxType", "dashboard-box-types", null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData56 = new CrudMetaFormData(null,"dashboard", true, true, null, 4.0, "Link", "Dashboard", "dashboards", null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData57 = new CrudMetaFormData(null,"width", true, true, null,5.0, "WIDTH_25,WIDTH_50,WIDTH_75,WIDTH_100", null, null, null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData58 = new CrudMetaFormData(null,"height", true, true, null, 6.0, "HEIGHT_25,HEIGHT_50,HEIGHT_75,HEIGHT_100", null, null, null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData59 = new CrudMetaFormData(null,"order", true, true, null, 7.0, "Integer", null, null, null, newCrudClassMetaData8);
        CrudMetaFormData crudMetaFormData60 = new CrudMetaFormData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData9);
        CrudMetaFormData crudMetaFormData61 = new CrudMetaFormData(null,"type", true, true, null, 2.0, "STATUS,CHART", null, null, null, newCrudClassMetaData9);
        CrudMetaFormData crudMetaFormData62 = new CrudMetaFormData(null,"kind", true, true, null, 3.0, "PIE_CHART,SERIAL_CHART,LINE_CHART,BAR_CHART,BUBBLE_CHART,FEEDBACK_STATUS, PROFIT_STATUS,ORDERS_STATUS,USERS_STATUS", null, null, null, newCrudClassMetaData9);
        CrudMetaFormData crudMetaFormData63 = new CrudMetaFormData(null,"dashboardBoxes", true, true, null, 4.0, "Linkset", "DashboardBox", "dashboard-boxes", null, newCrudClassMetaData9);
        CrudMetaFormData crudMetaFormData64 = new CrudMetaFormData(null, "username", true, true, null, 1.0, "String", null, null, null,newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData65 = new CrudMetaFormData(null, "password", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData66 = new CrudMetaFormData(null, "salt", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData67 = new CrudMetaFormData(null, "firstname", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData68 = new CrudMetaFormData(null, "surname", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData69 = new CrudMetaFormData(null, "email", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData70 = new CrudMetaFormData(null, "active", true, true, null, 7.0, "Boolean", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData71 = new CrudMetaFormData(null, "created", true, true, null, 8.0, "Data", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData72 = new CrudMetaFormData(null, "blocked", true, true, null, 9.0, "Boolean", null, null, null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData73 = new CrudMetaFormData(null, "roles", true, true, null, 10.0, "Linkset", "Role", "roles", null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData74 = new CrudMetaFormData(null, "customers", true, true, null, 11.0, "Linkset", "Customer", "customers", null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData75 = new CrudMetaFormData(null, "dashboards", true, true, null, 12.0, "Linkset", "Dashboard", "dashboards", null, newCrudClassMetaData5);
        CrudMetaFormData crudMetaFormData76 = new CrudMetaFormData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData10);
        CrudMetaFormData crudMetaFormData77 = new CrudMetaFormData(null,"permissions", true, true, null, 2.0, "Linkset", "Permission", "permissions", null, newCrudClassMetaData10);
        CrudMetaFormData crudMetaFormData78 = new CrudMetaFormData(null,"users", true, true, null, 3.0, "Linkset", "User", "users", null, newCrudClassMetaData10);
        CrudMetaFormData crudMetaFormData79 = new CrudMetaFormData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData11);
        CrudMetaFormData crudMetaFormData80 = new CrudMetaFormData(null,"roles", true, true, null, 2.0, "Linkset", "Role", "roles", null, newCrudClassMetaData11);
        CrudMetaFormData crudMetaFormData81 = new CrudMetaFormData(null,"className", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaFormData crudMetaFormData82 = new CrudMetaFormData(null,"titleColumns", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaFormData crudMetaFormData83 = new CrudMetaFormData(null,"editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData3);
        CrudMetaFormData crudMetaFormData84 = new CrudMetaFormData(null,"query", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaFormData crudMetaFormData85 = new CrudMetaFormData(null,"crudMetaFormData", true, true, null, 5.0, "Linkset", "CrudMetaFormData", "crud-meta-form-data", null, newCrudClassMetaData3);
        CrudMetaFormData crudMetaFormData86 = new CrudMetaFormData(null,"crudMetaGridData", true, true, null, 6.0, "Linkset", "CrudMetaGridData", "crud-meta-grid-data", null, newCrudClassMetaData3);
        crudMetaFormDataRepository.save(crudMetaFormData1);
        crudMetaFormDataRepository.save(crudMetaFormData2);
        crudMetaFormDataRepository.save(crudMetaFormData3);
        crudMetaFormDataRepository.save(crudMetaFormData4);
        crudMetaFormDataRepository.save(crudMetaFormData5);
        crudMetaFormDataRepository.save(crudMetaFormData6);
        crudMetaFormDataRepository.save(crudMetaFormData7);
        crudMetaFormDataRepository.save(crudMetaFormData8);
        crudMetaFormDataRepository.save(crudMetaFormData9);
        crudMetaFormDataRepository.save(crudMetaFormData10);
        crudMetaFormDataRepository.save(crudMetaFormData11);
        crudMetaFormDataRepository.save(crudMetaFormData12);
        crudMetaFormDataRepository.save(crudMetaFormData13);
        crudMetaFormDataRepository.save(crudMetaFormData14);
        crudMetaFormDataRepository.save(crudMetaFormData15);
        crudMetaFormDataRepository.save(crudMetaFormData16);
        crudMetaFormDataRepository.save(crudMetaFormData17);
        crudMetaFormDataRepository.save(crudMetaFormData18);
        crudMetaFormDataRepository.save(crudMetaFormData19);
        crudMetaFormDataRepository.save(crudMetaFormData20);
        crudMetaFormDataRepository.save(crudMetaFormData21);
        crudMetaFormDataRepository.save(crudMetaFormData22);
        crudMetaFormDataRepository.save(crudMetaFormData23);
        crudMetaFormDataRepository.save(crudMetaFormData24);
        crudMetaFormDataRepository.save(crudMetaFormData25);
        crudMetaFormDataRepository.save(crudMetaFormData26);
        crudMetaFormDataRepository.save(crudMetaFormData27);
        crudMetaFormDataRepository.save(crudMetaFormData28);
        crudMetaFormDataRepository.save(crudMetaFormData29);
        crudMetaFormDataRepository.save(crudMetaFormData30);
        crudMetaFormDataRepository.save(crudMetaFormData31);
        crudMetaFormDataRepository.save(crudMetaFormData32);
        crudMetaFormDataRepository.save(crudMetaFormData33);
        crudMetaFormDataRepository.save(crudMetaFormData34);
        crudMetaFormDataRepository.save(crudMetaFormData35);
        crudMetaFormDataRepository.save(crudMetaFormData36);
        crudMetaFormDataRepository.save(crudMetaFormData37);
        crudMetaFormDataRepository.save(crudMetaFormData38);
        crudMetaFormDataRepository.save(crudMetaFormData39);
        crudMetaFormDataRepository.save(crudMetaFormData40);
        crudMetaFormDataRepository.save(crudMetaFormData41);
        crudMetaFormDataRepository.save(crudMetaFormData42);
        crudMetaFormDataRepository.save(crudMetaFormData43);
        crudMetaFormDataRepository.save(crudMetaFormData44);
        crudMetaFormDataRepository.save(crudMetaFormData45);
        crudMetaFormDataRepository.save(crudMetaFormData46);
        crudMetaFormDataRepository.save(crudMetaFormData47);
        crudMetaFormDataRepository.save(crudMetaFormData48);
        crudMetaFormDataRepository.save(crudMetaFormData49);
        crudMetaFormDataRepository.save(crudMetaFormData50);
        crudMetaFormDataRepository.save(crudMetaFormData51);
        crudMetaFormDataRepository.save(crudMetaFormData52);
        crudMetaFormDataRepository.save(crudMetaFormData53);
        crudMetaFormDataRepository.save(crudMetaFormData54);
        crudMetaFormDataRepository.save(crudMetaFormData55);
        crudMetaFormDataRepository.save(crudMetaFormData56);
        crudMetaFormDataRepository.save(crudMetaFormData57);
        crudMetaFormDataRepository.save(crudMetaFormData58);
        crudMetaFormDataRepository.save(crudMetaFormData59);
        crudMetaFormDataRepository.save(crudMetaFormData60);
        crudMetaFormDataRepository.save(crudMetaFormData61);
        crudMetaFormDataRepository.save(crudMetaFormData62);
        crudMetaFormDataRepository.save(crudMetaFormData63);
        crudMetaFormDataRepository.save(crudMetaFormData64);
        crudMetaFormDataRepository.save(crudMetaFormData65);
        crudMetaFormDataRepository.save(crudMetaFormData66);
        crudMetaFormDataRepository.save(crudMetaFormData67);
        crudMetaFormDataRepository.save(crudMetaFormData68);
        crudMetaFormDataRepository.save(crudMetaFormData69);
        crudMetaFormDataRepository.save(crudMetaFormData70);
        crudMetaFormDataRepository.save(crudMetaFormData71);
        crudMetaFormDataRepository.save(crudMetaFormData72);
        crudMetaFormDataRepository.save(crudMetaFormData73);
        crudMetaFormDataRepository.save(crudMetaFormData74);
        crudMetaFormDataRepository.save(crudMetaFormData75);
        crudMetaFormDataRepository.save(crudMetaFormData76);
        crudMetaFormDataRepository.save(crudMetaFormData77);
        crudMetaFormDataRepository.save(crudMetaFormData78);
        crudMetaFormDataRepository.save(crudMetaFormData79);
        crudMetaFormDataRepository.save(crudMetaFormData80);
        crudMetaFormDataRepository.save(crudMetaFormData81);
        crudMetaFormDataRepository.save(crudMetaFormData82);
        crudMetaFormDataRepository.save(crudMetaFormData83);
        crudMetaFormDataRepository.save(crudMetaFormData84);
        crudMetaFormDataRepository.save(crudMetaFormData85);
        crudMetaFormDataRepository.save(crudMetaFormData86);
        CrudMetaGridData crudMetaGridData1 = new CrudMetaGridData(null, "fromProperty", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData2 = new CrudMetaGridData(null, "toProperty", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData3 = new CrudMetaGridData(null, "combineOperator", true, true, null, 3.0, "AND,OR,NOT", null, null, null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData4 = new CrudMetaGridData(null, "operator", true, true, null, 4.0, "EQUALS,MORE,LESS,MORE_OR_EQUALS,LESS_OR_EQUALS,MORE_OR_LESS,LIKE,BETWEEN,IS,INSTANCE_OF,MATCHES", null, null, null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData5 = new CrudMetaGridData(null, "crudMetaFormData", true, true, null, 3.0, "Link", "CrudMetaFormData", "crud-meta-form-data", null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData6 = new CrudMetaGridData(null, "crudMetaGridData", true, true, null, 4.0, "Link", "CrudMetaGridData", "crud-meta-grid-data", null, newCrudClassMetaData6);
        CrudMetaGridData crudMetaGridData7 = new CrudMetaGridData(null, "columnWidth", true, true, null, 1.0, "Double", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData8 = new CrudMetaGridData(null, "property", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData9 = new CrudMetaGridData(null, "editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData10 = new CrudMetaGridData(null, "visible", true, true, null, 4.0, "Boolean", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData11 = new CrudMetaGridData(null, "decorator", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData12 = new CrudMetaGridData(null, "order", true, true, null, 6.0, "Double", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData13 = new CrudMetaGridData(null, "crudClassMetaData", true, true, null, 7.0, "Link", "CrudClassMetaData", "crud-class-meta-data", null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData14 = new CrudMetaGridData(null, "bindingProperties", true, true, null, 8.0, "Linkset", "MetaDataPropertyBindingParameter", "meta-data-property-binding-parameters", null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData15 = new CrudMetaGridData(null, "type", true, true, null, 9.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData16 = new CrudMetaGridData(null, "linkedClass", true, true, null, 10.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData17 = new CrudMetaGridData(null, "linkedRepository", true, true, null, 11.0, "String", null, null, null, newCrudClassMetaData1);
        CrudMetaGridData crudMetaGridData18 = new CrudMetaGridData(null, "fieldLayoutGridPosition", true, true, null, 1.0, "String", null, null, null,newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData19 = new CrudMetaGridData(null, "property", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData20 = new CrudMetaGridData(null, "editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData21 = new CrudMetaGridData(null, "visible", true, true, null, 4.0, "Boolean", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData22 = new CrudMetaGridData(null, "decorator", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData23 = new CrudMetaGridData(null, "order", true, true, null, 6.0, "Double", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData24 = new CrudMetaGridData(null, "crudClassMetaData", true, true, null, 7.0, "Link", "CrudClassMetaData", "crud-class-meta-data", null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData25 = new CrudMetaGridData(null, "bindingProperties", true, true, null, 8.0, "Linkset", "MetaDataPropertyBindingParameter", "meta-data-property-binding-parameters", null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData26 = new CrudMetaGridData(null, "type", true, true, null, 9.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData27 = new CrudMetaGridData(null, "linkedClass", true, true, null, 10.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData28 = new CrudMetaGridData(null, "linkedRepository", true, true, null, 11.0, "String", null, null, null, newCrudClassMetaData2);
        CrudMetaGridData crudMetaGridData29 = new CrudMetaGridData(null,"customerId", true, true, null, 1.0, "Double", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData30 = new CrudMetaGridData(null,"companyName", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData31 = new CrudMetaGridData(null,"street", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData32 = new CrudMetaGridData(null,"street2", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData33 = new CrudMetaGridData(null,"postcode", true, true, null,5.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData34 = new CrudMetaGridData(null,"country", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData35 = new CrudMetaGridData(null,"city", true, true, null, 7.0, "String", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData36 = new CrudMetaGridData(null,"vatid", true, true, null, 8.0, "Double", null, null, null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData37 = new CrudMetaGridData(null,"contacts", true, true, null, 9.0, "Linkset", "CustomerContact", "customer-contacts", null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData38 = new CrudMetaGridData(null,"users", true, true, null, 10.0, "Linkset", "User", "users", null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData39 = new CrudMetaGridData(null,"parentCustomer", true, true, null, 11.0, "Link", "Customer", "customers", null, newCrudClassMetaData4);
        CrudMetaGridData crudMetaGridData40 = new CrudMetaGridData(null,"firstname", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData41 = new CrudMetaGridData(null,"surname", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData42 = new CrudMetaGridData(null,"phone", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData43 = new CrudMetaGridData(null,"mobilePhone", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData44 = new CrudMetaGridData(null,"fax", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData45 = new CrudMetaGridData(null,"emailAddress", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData46 = new CrudMetaGridData(null,"customer", true, true, null, 7.0, "Link", "Customer", "customers", null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData47 = new CrudMetaGridData(null,"type", true, true, null, 8.0, "CEO,TECHNICAL,PRIMARY", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData48 = new CrudMetaGridData(null,"salutation", true, true, null, 9.0, " MR,MRS", null, null, null, newCrudClassMetaData12);
        CrudMetaGridData crudMetaGridData49 = new CrudMetaGridData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData7);
        CrudMetaGridData crudMetaGridData50 = new CrudMetaGridData(null,"icon", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData7);
        CrudMetaGridData crudMetaGridData51 = new CrudMetaGridData(null,"user", true, true, null, 3.0, "Link", "User", "users", null, newCrudClassMetaData7);
        CrudMetaGridData crudMetaGridData52 = new CrudMetaGridData(null,"dashboardBoxes", true, true, null, 4.0, "Linkset", "DashboardBox", "dashboard-boxes", null, newCrudClassMetaData7);
        CrudMetaGridData crudMetaGridData53 = new CrudMetaGridData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData54 = new CrudMetaGridData(null,"description", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData55 = new CrudMetaGridData(null,"dashboardBoxType", true, true, null, 3.0, "Link", "DashboardBoxType", "dashboard-box-types", null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData56 = new CrudMetaGridData(null,"dashboard", true, true, null, 4.0, "Link", "Dashboard", "dashboards", null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData57 = new CrudMetaGridData(null,"width", true, true, null,5.0, "WIDTH_25,WIDTH_50,WIDTH_75,WIDTH_100", null, null, null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData58 = new CrudMetaGridData(null,"height", true, true, null, 6.0, "HEIGHT_25,HEIGHT_50,HEIGHT_75,HEIGHT_100", null, null, null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData59 = new CrudMetaGridData(null,"order", true, true, null, 7.0, "Integer", null, null, null, newCrudClassMetaData8);
        CrudMetaGridData crudMetaGridData60 = new CrudMetaGridData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData9);
        CrudMetaGridData crudMetaGridData61 = new CrudMetaGridData(null,"type", true, true, null, 2.0, "STATUS,CHART", null, null, null, newCrudClassMetaData9);
        CrudMetaGridData crudMetaGridData62 = new CrudMetaGridData(null,"kind", true, true, null, 3.0, "PIE_CHART,SERIAL_CHART,LINE_CHART,BAR_CHART,BUBBLE_CHART,FEEDBACK_STATUS, PROFIT_STATUS,ORDERS_STATUS,USERS_STATUS", null, null, null, newCrudClassMetaData9);
        CrudMetaGridData crudMetaGridData63 = new CrudMetaGridData(null,"dashboardBoxes", true, true, null, 4.0, "Linkset", "DashboardBox", "dashboard-boxes", null, newCrudClassMetaData9);
        CrudMetaGridData crudMetaGridData64 = new CrudMetaGridData(null, "username", true, true, null, 1.0, "String", null, null, null,newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData65 = new CrudMetaGridData(null, "password", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData66 = new CrudMetaGridData(null, "salt", true, true, null, 3.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData67 = new CrudMetaGridData(null, "firstname", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData68 = new CrudMetaGridData(null, "surname", true, true, null, 5.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData69 = new CrudMetaGridData(null, "email", true, true, null, 6.0, "String", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData70 = new CrudMetaGridData(null, "active", true, true, null, 7.0, "Boolean", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData71 = new CrudMetaGridData(null, "created", true, true, null, 8.0, "Data", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData72 = new CrudMetaGridData(null, "blocked", true, true, null, 9.0, "Boolean", null, null, null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData73 = new CrudMetaGridData(null, "roles", true, true, null, 10.0, "Linkset", "Role", "roles", null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData74 = new CrudMetaGridData(null, "customers", true, true, null, 11.0, "Linkset", "Customer", "customers", null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData75 = new CrudMetaGridData(null, "dashboards", true, true, null, 12.0, "Linkset", "Dashboard", "dashboards", null, newCrudClassMetaData5);
        CrudMetaGridData crudMetaGridData76 = new CrudMetaGridData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData10);
        CrudMetaGridData crudMetaGridData77 = new CrudMetaGridData(null,"permissions", true, true, null, 2.0, "Linkset", "Permission", "permissions", null, newCrudClassMetaData10);
        CrudMetaGridData crudMetaGridData78 = new CrudMetaGridData(null,"users", true, true, null, 3.0, "Linkset", "User", "users", null, newCrudClassMetaData10);
        CrudMetaGridData crudMetaGridData79 = new CrudMetaGridData(null,"name", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData11);
        CrudMetaGridData crudMetaGridData80 = new CrudMetaGridData(null,"roles", true, true, null, 2.0, "Linkset", "Role", "roles", null, newCrudClassMetaData11);
        CrudMetaGridData crudMetaGridData81 = new CrudMetaGridData(null,"className", true, true, null, 1.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaGridData crudMetaGridData82 = new CrudMetaGridData(null,"titleColumns", true, true, null, 2.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaGridData crudMetaGridData83 = new CrudMetaGridData(null,"editable", true, true, null, 3.0, "Boolean", null, null, null, newCrudClassMetaData3);
        CrudMetaGridData crudMetaGridData84 = new CrudMetaGridData(null,"query", true, true, null, 4.0, "String", null, null, null, newCrudClassMetaData3);
        CrudMetaGridData crudMetaGridData85 = new CrudMetaGridData(null,"crudMetaFormData", true, true, null, 5.0, "Linkset", "CrudMetaFormData", "crud-meta-form-data", null, newCrudClassMetaData3);
        CrudMetaGridData crudMetaGridData86 = new CrudMetaGridData(null,"crudMetaGridData", true, true, null, 6.0, "Linkset", "CrudMetaGridData", "crud-meta-grid-data", null, newCrudClassMetaData3);
        crudMetaGridDataRepository.save(crudMetaGridData1);
        crudMetaGridDataRepository.save(crudMetaGridData2);
        crudMetaGridDataRepository.save(crudMetaGridData3);
        crudMetaGridDataRepository.save(crudMetaGridData4);
        crudMetaGridDataRepository.save(crudMetaGridData5);
        crudMetaGridDataRepository.save(crudMetaGridData6);
        crudMetaGridDataRepository.save(crudMetaGridData7);
        crudMetaGridDataRepository.save(crudMetaGridData8);
        crudMetaGridDataRepository.save(crudMetaGridData9);
        crudMetaGridDataRepository.save(crudMetaGridData10);
        crudMetaGridDataRepository.save(crudMetaGridData11);
        crudMetaGridDataRepository.save(crudMetaGridData12);
        crudMetaGridDataRepository.save(crudMetaGridData13);
        crudMetaGridDataRepository.save(crudMetaGridData14);
        crudMetaGridDataRepository.save(crudMetaGridData15);
        crudMetaGridDataRepository.save(crudMetaGridData16);
        crudMetaGridDataRepository.save(crudMetaGridData17);
        crudMetaGridDataRepository.save(crudMetaGridData18);
        crudMetaGridDataRepository.save(crudMetaGridData19);
        crudMetaGridDataRepository.save(crudMetaGridData20);
        crudMetaGridDataRepository.save(crudMetaGridData21);
        crudMetaGridDataRepository.save(crudMetaGridData22);
        crudMetaGridDataRepository.save(crudMetaGridData23);
        crudMetaGridDataRepository.save(crudMetaGridData24);
        crudMetaGridDataRepository.save(crudMetaGridData25);
        crudMetaGridDataRepository.save(crudMetaGridData26);
        crudMetaGridDataRepository.save(crudMetaGridData27);
        crudMetaGridDataRepository.save(crudMetaGridData28);
        crudMetaGridDataRepository.save(crudMetaGridData29);
        crudMetaGridDataRepository.save(crudMetaGridData30);
        crudMetaGridDataRepository.save(crudMetaGridData31);
        crudMetaGridDataRepository.save(crudMetaGridData32);
        crudMetaGridDataRepository.save(crudMetaGridData33);
        crudMetaGridDataRepository.save(crudMetaGridData34);
        crudMetaGridDataRepository.save(crudMetaGridData35);
        crudMetaGridDataRepository.save(crudMetaGridData36);
        crudMetaGridDataRepository.save(crudMetaGridData37);
        crudMetaGridDataRepository.save(crudMetaGridData38);
        crudMetaGridDataRepository.save(crudMetaGridData39);
        crudMetaGridDataRepository.save(crudMetaGridData40);
        crudMetaGridDataRepository.save(crudMetaGridData41);
        crudMetaGridDataRepository.save(crudMetaGridData42);
        crudMetaGridDataRepository.save(crudMetaGridData43);
        crudMetaGridDataRepository.save(crudMetaGridData44);
        crudMetaGridDataRepository.save(crudMetaGridData45);
        crudMetaGridDataRepository.save(crudMetaGridData46);
        crudMetaGridDataRepository.save(crudMetaGridData47);
        crudMetaGridDataRepository.save(crudMetaGridData48);
        crudMetaGridDataRepository.save(crudMetaGridData49);
        crudMetaGridDataRepository.save(crudMetaGridData50);
        crudMetaGridDataRepository.save(crudMetaGridData51);
        crudMetaGridDataRepository.save(crudMetaGridData52);
        crudMetaGridDataRepository.save(crudMetaGridData53);
        crudMetaGridDataRepository.save(crudMetaGridData54);
        crudMetaGridDataRepository.save(crudMetaGridData55);
        crudMetaGridDataRepository.save(crudMetaGridData56);
        crudMetaGridDataRepository.save(crudMetaGridData57);
        crudMetaGridDataRepository.save(crudMetaGridData58);
        crudMetaGridDataRepository.save(crudMetaGridData59);
        crudMetaGridDataRepository.save(crudMetaGridData60);
        crudMetaGridDataRepository.save(crudMetaGridData61);
        crudMetaGridDataRepository.save(crudMetaGridData62);
        crudMetaGridDataRepository.save(crudMetaGridData63);
        crudMetaGridDataRepository.save(crudMetaGridData64);
        crudMetaGridDataRepository.save(crudMetaGridData65);
        crudMetaGridDataRepository.save(crudMetaGridData66);
        crudMetaGridDataRepository.save(crudMetaGridData67);
        crudMetaGridDataRepository.save(crudMetaGridData68);
        crudMetaGridDataRepository.save(crudMetaGridData69);
        crudMetaGridDataRepository.save(crudMetaGridData70);
        crudMetaGridDataRepository.save(crudMetaGridData71);
        crudMetaGridDataRepository.save(crudMetaGridData72);
        crudMetaGridDataRepository.save(crudMetaGridData73);
        crudMetaGridDataRepository.save(crudMetaGridData74);
        crudMetaGridDataRepository.save(crudMetaGridData75);
        crudMetaGridDataRepository.save(crudMetaGridData76);
        crudMetaGridDataRepository.save(crudMetaGridData77);
        crudMetaGridDataRepository.save(crudMetaGridData78);
        crudMetaGridDataRepository.save(crudMetaGridData79);
        crudMetaGridDataRepository.save(crudMetaGridData80);
        crudMetaGridDataRepository.save(crudMetaGridData81);
        crudMetaGridDataRepository.save(crudMetaGridData82);
        crudMetaGridDataRepository.save(crudMetaGridData83);
        crudMetaGridDataRepository.save(crudMetaGridData84);
        crudMetaGridDataRepository.save(crudMetaGridData85);
        crudMetaGridDataRepository.save(crudMetaGridData86);
        MetaDataPropertyBindingParameter metaDataPropertyBindingParameter = new MetaDataPropertyBindingParameter(null, "customer", "@rid");
        metaDataPropertyBindingParameter.setCombineOperator(CombineOperator.OR);
        metaDataPropertyBindingParameter.setOperator(Operator.EQUALS);
        metaDataPropertyBindingParameterRepository.save(metaDataPropertyBindingParameter);
        Customer customer = new Customer(null, 1.0, "SMSC", "Amtsgericht", "Amtsgericht", "3254", "Germany", "Stuttgart", 5672394.0);
        Set<User> users = new HashSet<>(userRepository.findAllDistinctByOrderById());
        customer.setUsers(users);
        Customer newCustomer = customerRepository.save(customer);
        CustomerContact customerContact = new CustomerContact(null, "SMSC", "SMSC", "0674329568", "0504569753", "fake_fax", "smsc@bulk.io", Type.CEO, Salutation.MR);
        customerContact.setCustomer(newCustomer);
        customerContactRepository.save(customerContact);
        Dashboard dashboard = new Dashboard(null, "default", "user", new_user);
        Dashboard newDashboard = dashboardRepository.save(dashboard);
        DashboardBoxType dashboardBoxType1 = new DashboardBoxType(null, "Ivan feeds", io.smsc.model.dashboard.Type.STATUS, Kind.FEEDBACK_STATUS);
        DashboardBoxType dashboardBoxType2 = new DashboardBoxType(null, "Petia profit", io.smsc.model.dashboard.Type.CHART, Kind.PIE_CHART);
        DashboardBoxType dashboardBoxType3 = new DashboardBoxType(null, "Rusia chart profit", io.smsc.model.dashboard.Type.CHART, Kind.SERIAL_CHART);
        DashboardBoxType dashboardBoxType4 = new DashboardBoxType(null, "Ivan chart profit", io.smsc.model.dashboard.Type.CHART, Kind.LINE_CHART);
        DashboardBoxType dashboardBoxType5 = new DashboardBoxType(null, "Kolia chart profit", io.smsc.model.dashboard.Type.CHART, Kind.BAR_CHART);
        DashboardBoxType dashboardBoxType6 = new DashboardBoxType(null, "Masha bubble chartat", io.smsc.model.dashboard.Type.CHART, Kind.BUBBLE_CHART);
        DashboardBoxType newDashboardBoxType1 = dashboardBoxTypeRepository.save(dashboardBoxType1);
        DashboardBoxType newDashboardBoxType2 = dashboardBoxTypeRepository.save(dashboardBoxType2);
        DashboardBoxType newDashboardBoxType3 = dashboardBoxTypeRepository.save(dashboardBoxType3);
        DashboardBoxType newDashboardBoxType4 = dashboardBoxTypeRepository.save(dashboardBoxType4);
        DashboardBoxType newDashboardBoxType5 = dashboardBoxTypeRepository.save(dashboardBoxType5);
        DashboardBoxType newDashboardBoxType6 = dashboardBoxTypeRepository.save(dashboardBoxType6);
        DashboardBox dashboardBox1 = new DashboardBox(null, Width.WIDTH_25, Height.HEIGHT_25, 1, "Box 1", "Box 1 desc", newDashboard, newDashboardBoxType1);
        DashboardBox dashboardBox2 = new DashboardBox(null, Width.WIDTH_25, Height.HEIGHT_25, 2, "Box 2", "Box 2 desc", newDashboard, newDashboardBoxType1);
        DashboardBox dashboardBox3 = new DashboardBox(null, Width.WIDTH_25, Height.HEIGHT_25, 3, "Box 3", "Box 3 desc", newDashboard, newDashboardBoxType1);
        DashboardBox dashboardBox4 = new DashboardBox(null, Width.WIDTH_25, Height.HEIGHT_25, 4, "Box 4", "Box 4 desc", newDashboard, newDashboardBoxType1);
        DashboardBox dashboardBox5 = new DashboardBox(null, Width.WIDTH_50, Height.HEIGHT_50, 5, "Box 5", "Box 5 desc", newDashboard, newDashboardBoxType2);
        DashboardBox dashboardBox6 = new DashboardBox(null, Width.WIDTH_50, Height.HEIGHT_50, 6, "Box 6", "Box 6 desc", newDashboard, newDashboardBoxType3);
        DashboardBox dashboardBox7 = new DashboardBox(null, Width.WIDTH_50, Height.HEIGHT_50, 7, "Box 7", "Box 7 desc", newDashboard, newDashboardBoxType4);
        DashboardBox dashboardBox8 = new DashboardBox(null, Width.WIDTH_50, Height.HEIGHT_50, 8, "Box 8", "Box 8 desc", newDashboard, newDashboardBoxType5);
        DashboardBox dashboardBox9 = new DashboardBox(null, Width.WIDTH_50, Height.HEIGHT_50, 9, "Box 9", "Box 9 desc", newDashboard, newDashboardBoxType6);
        dashboardBoxRepository.save(dashboardBox1);
        dashboardBoxRepository.save(dashboardBox2);
        dashboardBoxRepository.save(dashboardBox3);
        dashboardBoxRepository.save(dashboardBox4);
        dashboardBoxRepository.save(dashboardBox5);
        dashboardBoxRepository.save(dashboardBox6);
        dashboardBoxRepository.save(dashboardBox7);
        dashboardBoxRepository.save(dashboardBox8);
        dashboardBoxRepository.save(dashboardBox9);
    }
}
