package io.smsc.db.migration;

import io.smsc.model.Role;
import io.smsc.model.User;
import io.smsc.repository.permission.PermissionRepository;
import io.smsc.repository.role.RoleRepository;
import io.smsc.repository.user.UserRepository;
import io.smsc.repository.user.UserRepositoryImpl;
import org.flywaydb.core.api.migration.spring.SpringJdbcMigration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class V2__populateDB implements SpringJdbcMigration {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserRepositoryImpl userRepositoryImpl;

    @Autowired
    private RoleRepository roleRepository;

    @Autowired
    private PermissionRepository permissionRepository;

    public void migrate(JdbcTemplate jdbcTemplate) {
        roleRepository.save(new Role(3L, "ROLE_USER"));
//        User user = new User(1L,"User1","password","userName","userSurname","user@gmail.com",true,false);
//        User admin = new User(2L,"Admin1","admin","adminName","adminSurname","admin@gmail.com",true,false);
//        PopulateDB.saveUser(user);
//        PopulateDB.saveUser(admin);
//        jdbcTemplate.execute("INSERT INTO ROLE (ID, NAME) VALUES (3, 'ROLE_USER')");
//        jdbcTemplate.execute("INSERT INTO ROLE (ID, NAME) VALUES (4, 'ROLE_ADMIN')");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (5, 'READ_USER');");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (6, 'UPDATE_USER');");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (7, 'CREATE_USER');");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (8, 'DELETE_USER');");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (9, 'READ_OWN_USER')");
//        jdbcTemplate.execute("INSERT INTO PERMISSION (ID, NAME) VALUES (10, 'UPDATE_OWN_USER')");
//        jdbcTemplate.execute("INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 3)");
//        jdbcTemplate.execute("INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 4)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (3, 9)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (3, 10)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 5)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 6)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 7)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 8)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 9)");
//        jdbcTemplate.execute("INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 10)");
//        jdbcTemplate.execute("INSERT INTO CRUD_CLASS_META_DATA (ID, CLASS_NAME, TITLE_COLUMNS, EDITABLE, QUERY_NAME) VALUES (11, 'CrudMetaGridData', 'columnWidth', TRUE, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_CLASS_META_DATA (ID, CLASS_NAME, TITLE_COLUMNS, EDITABLE, QUERY_NAME) VALUES (12, 'CrudMetaFormData', 'fieldLayoutGridPosition', TRUE, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_CLASS_META_DATA (ID, CLASS_NAME, TITLE_COLUMNS, EDITABLE, QUERY_NAME) VALUES (13, 'CrudClassMetaData', 'class', TRUE, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_CLASS_META_DATA (ID, CLASS_NAME, TITLE_COLUMNS, EDITABLE, QUERY_NAME) VALUES (14, 'MetaDataPropertyBindingParameter', 'operator', TRUE, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (15, 'fromProperty', TRUE, TRUE, NULL, 1.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (16, 'toProperty', TRUE, TRUE, NULL, 2.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (17, 'combineOperator', TRUE, TRUE, NULL, 3.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (18, 'operator', TRUE, TRUE, NULL, 4.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (19, 'columnWidth', TRUE, TRUE, NULL, 1.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (20, 'property', TRUE, TRUE, NULL, 2.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (21, 'editable', TRUE, TRUE, NULL, 3.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (22, 'visible', TRUE, TRUE, NULL, 4.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (23, 'decorator', TRUE, TRUE, NULL, 5.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (24, 'order', TRUE, TRUE, NULL, 6.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (25, 'crudClassMetaData', TRUE, TRUE, NULL, 7.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (26, 'bingingProperties', TRUE, TRUE, NULL, 8.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (27, 'fieldLayoutGridPosition', TRUE, TRUE, NULL, 1.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (28, 'property', TRUE, TRUE, NULL, 2.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (29, 'editable', TRUE, TRUE, NULL, 3.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (30, 'visible', TRUE, TRUE, NULL, 4.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (31, 'decorator', TRUE, TRUE, NULL, 5.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (32, 'order', TRUE, TRUE, NULL, 6.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (33, 'crudClassMetaData', TRUE, TRUE, NULL, 7.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_GRID_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, COLUMN_WIDTH) VALUES (34, 'bingingProperties', TRUE, TRUE, NULL, 8.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (35, 'fromProperty', TRUE, TRUE, NULL, 1.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (36, 'toProperty', TRUE, TRUE, NULL, 2.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (37, 'combineOperator', TRUE, TRUE, NULL, 3.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (38, 'operator', TRUE, TRUE, NULL, 4.0, 14, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (39, 'columnWidth', TRUE, TRUE, NULL, 1.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (40, 'property', TRUE, TRUE, NULL, 2.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (41, 'editable', TRUE, TRUE, NULL, 3.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (42, 'visible', TRUE, TRUE, NULL, 4.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (43, 'decorator', TRUE, TRUE, NULL, 5.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (44, 'order', TRUE, TRUE, NULL, 6.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (45, 'crudClassMetaData', TRUE, TRUE, NULL, 7.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (46, 'bingingProperties', TRUE, TRUE, NULL, 8.0, 11, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (47, 'fieldLayoutGridPosition', TRUE, TRUE, NULL, 1.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (48, 'property', TRUE, TRUE, NULL, 2.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (49, 'editable', TRUE, TRUE, NULL, 3.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (50, 'visible', TRUE, TRUE, NULL, 4.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (51, 'decorator', TRUE, TRUE, NULL, 5.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (52, 'order', TRUE, TRUE, NULL, 6.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (53, 'crudClassMetaData', TRUE, TRUE, NULL, 7.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO CRUD_META_FORM_DATA (ID, PROPERTY, EDITABLE, VISIBLE, DECORATOR, ORDER_NUMBER, CRUD_CLASS_META_DATA, FIELD_LAYOUT_GRID_POSITION) VALUES (54, 'bingingProperties', TRUE, TRUE, NULL, 8.0, 12, NULL)");
//        jdbcTemplate.execute("INSERT INTO META_DATA_PROPERTY_BINDING_PARAMETER (ID, FROM_PROPERTY, TO_PROPERTY) VALUES (55, 'customer', '@rid')");
//        jdbcTemplate.execute("INSERT INTO META_DATA_PROPERTY_BINDING_PARAMETER_COMBINE_OPERATOR (META_DATA_PROPERTY_BINDING_PARAMETER_ID, COMBINE_OPERATOR) VALUES (55, 'OR')");
//        jdbcTemplate.execute("INSERT INTO META_DATA_PROPERTY_BINDING_PARAMETER_OPERATOR (META_DATA_PROPERTY_BINDING_PARAMETER_ID, OPERATOR) VALUES (55, 'EQUALS')");
    }
}
