CREATE TABLE MNC (
  ID                  BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  CREATED_DATE        TIMESTAMP    NOT NULL,
  LAST_MODIFIED_DATE  TIMESTAMP    NOT NULL,
  VERSION             BIGINT       NOT NULL,
  CARRIER             VARCHAR(255) NOT NULL,
  MNC                 INTEGER      NOT NULL,
  CREATED_BY_ID       BIGINT,
  LAST_MODIFIED_BY_ID BIGINT,
  MCC                 INTEGER      NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE MNC
  ADD CONSTRAINT mnc_unique_mnc_mcc_idx UNIQUE (MCC, MNC);

CREATE INDEX fk_mcc_idx
  ON MNC (MCC);

ALTER TABLE MNC
  ADD CONSTRAINT FK_bjfb3oinb3s8qy9q3dctxb50i
FOREIGN KEY (MCC)
REFERENCES MCC ON UPDATE CASCADE;

INSERT INTO ADMIN_USER_GROUP (NAME, LAST_MODIFIED_DATE, VERSION, CREATED_DATE, CREATED_BY_ID, LAST_MODIFIED_BY_ID) VALUES
  ('MNC_ADMIN', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_READ_ONLY', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin'));

INSERT INTO ADMIN_USER_AUTHORITY (NAME, LAST_MODIFIED_DATE, VERSION, CREATED_DATE, CREATED_BY_ID, LAST_MODIFIED_BY_ID) VALUES
  ('MNC_READ', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_WRITE', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_CREATE', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_DELETE', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_EXISTS', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin')),
  ('MNC_COUNT', current_timestamp, 0, current_timestamp, (select id from user_account where username = 'admin'),
   (select id from user_account where username = 'admin'));

INSERT INTO ADMIN_USER_GROUP_AUTHORITY (GROUP_ID, AUTHORITY_ID) VALUES
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_READ')),
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_WRITE')),
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_CREATE')),
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_DELETE')),
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_EXISTS')),
  ((select id from admin_user_group where name = 'MNC_ADMIN'), (select id from admin_user_authority where name = 'MNC_COUNT')),
  ((select id from admin_user_group where name = 'MNC_READ_ONLY'), (select id from admin_user_authority where name = 'MNC_READ'));

INSERT INTO ADMIN_USER_GROUP_USER (USER_ID, GROUP_ID) VALUES
  ((select id from user_account where username = 'user'), (select id from admin_user_group where name = 'MNC_ADMIN')),
  ((select id from user_account where username = 'demo'), (select id from admin_user_group where name = 'MNC_READ_ONLY'));



