CREATE SEQUENCE customer_contact_seq;

CREATE SEQUENCE customer_seq START WITH 40000 INCREMENT BY 1;

CREATE SEQUENCE customer_user_account_seq;

CREATE SEQUENCE dashboard_box_seq;

CREATE SEQUENCE dashboard_box_type_seq;

CREATE SEQUENCE dashboard_seq;

CREATE SEQUENCE role_seq;

CREATE SEQUENCE user_account_seq;

CREATE TABLE CUSTOMER (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  CITY               VARCHAR2(255 CHAR) NOT NULL,
  COMPANY_NAME       VARCHAR2(255 CHAR) NOT NULL,
  COUNTRY            VARCHAR2(255 CHAR) NOT NULL,
  POSTCODE           VARCHAR2(255 CHAR) NOT NULL,
  STREET             VARCHAR2(255 CHAR) NOT NULL,
  STREET2            VARCHAR2(255 CHAR) NOT NULL,
  VATID              VARCHAR2(255 CHAR),
  PARENT_ID          NUMBER(19, 0),
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER_CONTACT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  EMAIL_ADDRESS      VARCHAR2(255 CHAR) NOT NULL,
  FAX                VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  MOBILE_PHONE       VARCHAR2(255 CHAR) NOT NULL,
  PHONE              VARCHAR2(255 CHAR) NOT NULL,
  SALUTATION         VARCHAR2(255 CHAR) NOT NULL,
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  TYPE               VARCHAR2(255 CHAR) NOT NULL,
  CUSTOMER_ID        NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER_USER_ACCOUNT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ACTIVE             NUMBER(1, 0)       NOT NULL,
  BLOCKED            NUMBER(1, 0)       NOT NULL,
  CREATED            TIMESTAMP          NOT NULL,
  EMAIL              VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  PASSWORD           VARCHAR2(255 CHAR) NOT NULL,
  SALT               VARCHAR2(255 CHAR),
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  USERNAME           VARCHAR2(255 CHAR) NOT NULL,
  SALUTATION         VARCHAR2(255 CHAR) NOT NULL,
  CUSTOMER_ID        NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ICON               VARCHAR2(255 CHAR) NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  USER_ACCOUNT_ID    NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD_BOX (
  ID                    NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE    TIMESTAMP          NOT NULL,
  VERSION               NUMBER(19, 0)      NOT NULL,
  DESCRIPTION           VARCHAR2(255 CHAR) NOT NULL,
  HEIGHT                VARCHAR2(255 CHAR) NOT NULL,
  NAME                  VARCHAR2(255 CHAR) NOT NULL,
  ORDER_NUMBER          NUMBER(10, 0)      NOT NULL,
  WIDTH                 VARCHAR2(255 CHAR) NOT NULL,
  DASHBOARD_ID          NUMBER(19, 0)      NOT NULL,
  DASHBOARD_BOX_TYPE_ID NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD_BOX_TYPE (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  KIND               VARCHAR2(255 CHAR) NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  TYPE               VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ACCOUNT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ACTIVE             NUMBER(1, 0)       NOT NULL,
  BLOCKED            NUMBER(1, 0)       NOT NULL,
  CREATED            TIMESTAMP          NOT NULL,
  EMAIL              VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  PASSWORD           VARCHAR2(255 CHAR) NOT NULL,
  SALT               VARCHAR2(255 CHAR),
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  USERNAME           VARCHAR2(255 CHAR) NOT NULL,
  SALUTATION         VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
  USER_ID NUMBER(19, 0) NOT NULL,
  ROLE_ID NUMBER(19, 0) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE CUSTOMER_CONTACT
  ADD CONSTRAINT UK_rt1h2souk5fkc2l0yojlch8ng UNIQUE (EMAIL_ADDRESS);

ALTER TABLE CUSTOMER_USER_ACCOUNT
  ADD CONSTRAINT UK_ocoo1ta18u6p16unw7h8b7i8h UNIQUE (USERNAME);

ALTER TABLE DASHBOARD
  ADD CONSTRAINT UK_k452w4cpbviagh85ll1q6gfc UNIQUE (NAME);

ALTER TABLE DASHBOARD_BOX_TYPE
  ADD CONSTRAINT UK_calopw9wexb9vek0fnkaotp2n UNIQUE (NAME);

ALTER TABLE ROLE
  ADD CONSTRAINT UK_lqaytvswxwacb7s84gcw7tk7l UNIQUE (NAME);

ALTER TABLE USER_ACCOUNT
  ADD CONSTRAINT UK_5b1ufubngfek527jhb11aure0 UNIQUE (USERNAME);

ALTER TABLE CUSTOMER
  ADD CONSTRAINT FK_k3k4147v3m5pjyjgfcrs0cdpj
FOREIGN KEY (PARENT_ID)
REFERENCES CUSTOMER;

ALTER TABLE CUSTOMER_CONTACT
  ADD CONSTRAINT FK_32q3wpxac3cbvhn1t9bxmcr81
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER
ON DELETE CASCADE;

ALTER TABLE CUSTOMER_USER_ACCOUNT
  ADD CONSTRAINT FK_jup37owwps8o8ntgoxdmn0th2
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER
ON DELETE CASCADE;

ALTER TABLE DASHBOARD
  ADD CONSTRAINT FK_agttn8ptawhkdx8qse4hnkvpr
FOREIGN KEY (USER_ACCOUNT_ID)
REFERENCES USER_ACCOUNT
ON DELETE CASCADE;

ALTER TABLE DASHBOARD_BOX
  ADD CONSTRAINT FK_dgep5oi78i2irrmue308doxrp
FOREIGN KEY (DASHBOARD_ID)
REFERENCES DASHBOARD
ON DELETE CASCADE;

ALTER TABLE DASHBOARD_BOX
  ADD CONSTRAINT FK_pdct77x9bvtflrsx224gkvhhs
FOREIGN KEY (DASHBOARD_BOX_TYPE_ID)
REFERENCES DASHBOARD_BOX_TYPE
ON DELETE CASCADE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_oqmdk7xj0ainhxpvi79fkaq3y
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_j2j8kpywaghe8i36swcxv8784
FOREIGN KEY (USER_ID)
REFERENCES USER_ACCOUNT;