CREATE SEQUENCE acl_class_seq;

CREATE SEQUENCE acl_entry_seq;

CREATE SEQUENCE acl_object_identity_seq;

CREATE SEQUENCE acl_sid_seq;

CREATE SEQUENCE customer_contact_seq;

CREATE SEQUENCE customer_seq START WITH 40000 INCREMENT BY 1;

CREATE SEQUENCE customer_user_account_seq;

CREATE SEQUENCE dashboard_box_seq;

CREATE SEQUENCE dashboard_box_type_seq;

CREATE SEQUENCE dashboard_seq;

CREATE SEQUENCE role_seq;

CREATE SEQUENCE user_account_seq;

CREATE TABLE ACL_CLASS (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  CLASS              VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ACL_ENTRY (
  ID                  NUMBER(19, 0) NOT NULL,
  LAST_MODIFIED_DATE  TIMESTAMP     NOT NULL,
  VERSION             NUMBER(19, 0) NOT NULL,
  ACE_ORDER           NUMBER(10, 0) NOT NULL,
  AUDIT_FAILURE       NUMBER(1, 0)  NOT NULL,
  AUDIT_SUCCESS       NUMBER(1, 0)  NOT NULL,
  GRANTING            NUMBER(1, 0)  NOT NULL,
  MASK                NUMBER(10, 0) NOT NULL,
  ACL_OBJECT_IDENTITY NUMBER(19, 0) NOT NULL,
  SID                 NUMBER(19, 0) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ACL_OBJECT_IDENTITY (
  ID                 NUMBER(19, 0) NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP     NOT NULL,
  VERSION            NUMBER(19, 0) NOT NULL,
  ENTRIES_INHERITING NUMBER(1, 0)  NOT NULL,
  OBJECT_ID_IDENTITY NUMBER(19, 0) NOT NULL,
  OBJECT_ID_CLASS    NUMBER(19, 0) NOT NULL,
  OWNER_SID          NUMBER(19, 0) NOT NULL,
  PARENT_OBJECT      NUMBER(19, 0),
  PRIMARY KEY (ID)
);

CREATE TABLE ACL_SID (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  PRINCIPAL          NUMBER(1, 0)       NOT NULL,
  SID                VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  CITY               VARCHAR2(255 CHAR) NOT NULL,
  COMPANY_NAME       VARCHAR2(255 CHAR) NOT NULL,
  COUNTRY            VARCHAR2(255 CHAR) NOT NULL,
  POSTCODE           VARCHAR2(255 CHAR) NOT NULL,
  STREET             VARCHAR2(255 CHAR) NOT NULL,
  STREET2            VARCHAR2(255 CHAR) NOT NULL,
  VATID              DOUBLE PRECISION,
  PARENT_ID          NUMBER(19, 0),
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER_CONTACT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  EMAIL_ADDRESS      VARCHAR2(255 CHAR) NOT NULL,
  FAX                VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  MOBILE_PHONE       VARCHAR2(255 CHAR) NOT NULL,
  PHONE              VARCHAR2(255 CHAR) NOT NULL,
  SALUTATION         VARCHAR2(255 CHAR) NOT NULL,
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  TYPE               VARCHAR2(255 CHAR) NOT NULL,
  CUSTOMER_ID        NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER_USER_ACCOUNT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ACTIVE             NUMBER(1, 0)       NOT NULL,
  BLOCKED            NUMBER(1, 0)       NOT NULL,
  CREATED            TIMESTAMP          NOT NULL,
  EMAIL              VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  PASSWORD           VARCHAR2(255 CHAR) NOT NULL,
  SALT               VARCHAR2(255 CHAR),
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  USERNAME           VARCHAR2(255 CHAR) NOT NULL,
  CUSTOMER_ID        NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ICON               VARCHAR2(255 CHAR) NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  USER_ACCOUNT_ID    NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD_BOX (
  ID                    NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE    TIMESTAMP          NOT NULL,
  VERSION               NUMBER(19, 0)      NOT NULL,
  DESCRIPTION           VARCHAR2(255 CHAR) NOT NULL,
  HEIGHT                VARCHAR2(255 CHAR) NOT NULL,
  NAME                  VARCHAR2(255 CHAR) NOT NULL,
  ORDER_NUMBER          NUMBER(10, 0)      NOT NULL,
  WIDTH                 VARCHAR2(255 CHAR) NOT NULL,
  DASHBOARD_ID          NUMBER(19, 0)      NOT NULL,
  DASHBOARD_BOX_TYPE_ID NUMBER(19, 0)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD_BOX_TYPE (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  KIND               VARCHAR2(255 CHAR) NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  TYPE               VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  NAME               VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ACCOUNT (
  ID                 NUMBER(19, 0)      NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  VERSION            NUMBER(19, 0)      NOT NULL,
  ACTIVE             NUMBER(1, 0)       NOT NULL,
  BLOCKED            NUMBER(1, 0)       NOT NULL,
  CREATED            TIMESTAMP          NOT NULL,
  EMAIL              VARCHAR2(255 CHAR) NOT NULL,
  FIRST_NAME         VARCHAR2(255 CHAR) NOT NULL,
  PASSWORD           VARCHAR2(255 CHAR) NOT NULL,
  SALT               VARCHAR2(255 CHAR),
  SURNAME            VARCHAR2(255 CHAR) NOT NULL,
  USERNAME           VARCHAR2(255 CHAR) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
  USER_ID NUMBER(19, 0) NOT NULL,
  ROLE_ID NUMBER(19, 0) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE ACL_CLASS
  ADD CONSTRAINT UK_b9jm6yrofuhriaet5qlvaa2sb UNIQUE (CLASS);

ALTER TABLE ACL_ENTRY
  ADD CONSTRAINT acl_identity_order_idx UNIQUE (ACL_OBJECT_IDENTITY, ACE_ORDER);

ALTER TABLE ACL_ENTRY
  ADD CONSTRAINT UK_2udy4xgijqxsi2enlqmp1ryoi UNIQUE (ACE_ORDER);

ALTER TABLE ACL_ENTRY
  ADD CONSTRAINT UK_4rfb2hf1mgefbvivqlb3uhc1o UNIQUE (ACL_OBJECT_IDENTITY);

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT acl_class_identity_idx UNIQUE (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY);

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT UK_sqoxny9iftavslu22wdw45s5j UNIQUE (OBJECT_ID_IDENTITY);

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT UK_93h9hjf8xedn5xo7gagsy6fth UNIQUE (OBJECT_ID_CLASS);

ALTER TABLE ACL_SID
  ADD CONSTRAINT acl_sid_principal_idx UNIQUE (SID, PRINCIPAL);

ALTER TABLE ACL_SID
  ADD CONSTRAINT UK_iffjecpr10qe7c08yilqi4mi6 UNIQUE (SID);

ALTER TABLE CUSTOMER_CONTACT
  ADD CONSTRAINT UK_rt1h2souk5fkc2l0yojlch8ng UNIQUE (EMAIL_ADDRESS);

ALTER TABLE CUSTOMER_USER_ACCOUNT
  ADD CONSTRAINT UK_ocoo1ta18u6p16unw7h8b7i8h UNIQUE (USERNAME);

ALTER TABLE DASHBOARD
  ADD CONSTRAINT UK_k452w4cpbviagh85ll1q6gfc UNIQUE (NAME);

ALTER TABLE DASHBOARD_BOX_TYPE
  ADD CONSTRAINT UK_calopw9wexb9vek0fnkaotp2n UNIQUE (NAME);

ALTER TABLE ROLE
  ADD CONSTRAINT UK_lqaytvswxwacb7s84gcw7tk7l UNIQUE (NAME);

ALTER TABLE USER_ACCOUNT
  ADD CONSTRAINT UK_5b1ufubngfek527jhb11aure0 UNIQUE (USERNAME);

ALTER TABLE ACL_ENTRY
  ADD CONSTRAINT FK_4rfb2hf1mgefbvivqlb3uhc1o
FOREIGN KEY (ACL_OBJECT_IDENTITY)
REFERENCES ACL_OBJECT_IDENTITY;

ALTER TABLE ACL_ENTRY
  ADD CONSTRAINT FK_pwqqgnc867uhlp6ra8f6cu44d
FOREIGN KEY (SID)
REFERENCES ACL_SID;

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT FK_93h9hjf8xedn5xo7gagsy6fth
FOREIGN KEY (OBJECT_ID_CLASS)
REFERENCES ACL_CLASS;

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT FK_47mv8is8lo3t2rm4n7a9oatpy
FOREIGN KEY (OWNER_SID)
REFERENCES ACL_SID;

ALTER TABLE ACL_OBJECT_IDENTITY
  ADD CONSTRAINT FK_osevoaw0w5t99q4x25r4ohkm2
FOREIGN KEY (PARENT_OBJECT)
REFERENCES ACL_OBJECT_IDENTITY;

ALTER TABLE CUSTOMER
  ADD CONSTRAINT FK_k3k4147v3m5pjyjgfcrs0cdpj
FOREIGN KEY (PARENT_ID)
REFERENCES CUSTOMER;

ALTER TABLE CUSTOMER_CONTACT
  ADD CONSTRAINT FK_32q3wpxac3cbvhn1t9bxmcr81
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER
ON DELETE CASCADE;

ALTER TABLE CUSTOMER_USER_ACCOUNT
  ADD CONSTRAINT FK_jup37owwps8o8ntgoxdmn0th2
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER
ON DELETE CASCADE;

ALTER TABLE DASHBOARD
  ADD CONSTRAINT FK_agttn8ptawhkdx8qse4hnkvpr
FOREIGN KEY (USER_ACCOUNT_ID)
REFERENCES USER_ACCOUNT
ON DELETE CASCADE;

ALTER TABLE DASHBOARD_BOX
  ADD CONSTRAINT FK_dgep5oi78i2irrmue308doxrp
FOREIGN KEY (DASHBOARD_ID)
REFERENCES DASHBOARD
ON DELETE CASCADE;

ALTER TABLE DASHBOARD_BOX
  ADD CONSTRAINT FK_pdct77x9bvtflrsx224gkvhhs
FOREIGN KEY (DASHBOARD_BOX_TYPE_ID)
REFERENCES DASHBOARD_BOX_TYPE
ON DELETE CASCADE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_oqmdk7xj0ainhxpvi79fkaq3y
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT FK_j2j8kpywaghe8i36swcxv8784
FOREIGN KEY (USER_ID)
REFERENCES USER_ACCOUNT;